# Pystern Blot
# SPDX-License-Identifier: GPL-3.0-only
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3 of the License.

from __future__ import annotations

from pathlib import Path

from PySide6.QtWidgets import QGraphicsScene
from PySide6.QtGui import QFont, QPixmap
from PySide6.QtCore import QRectF, Qt

from .models import Project
from .ui.crop_rect_item import CropRectItem


def _load_original_pixmap(workspace_root: Path, sha256: str) -> QPixmap:
    """
    Loads assets/<sha256>/original.* using Qt image plugins.
    Note: Qt may fail on some 16-bit TIFFs. If you hit that, tell me and we’ll switch loader.
    """
    asset_dir = workspace_root / "assets" / sha256
    for p in asset_dir.glob("original.*"):
        pm = QPixmap(str(p))
        if not pm.isNull():
            return pm
    return QPixmap()

def _load_preview_crop_pixmap(workspace_root: Path, sha256: str) -> QPixmap:
    """
    Loads assets/<sha256>/preview_crop.png (generated by Workspace).
    """
    p = workspace_root / "assets" / sha256 / "preview_crop.png"
    pm = QPixmap(str(p)) if p.exists() else QPixmap()
    return pm


def build_panel_scene(project: Project, workspace_root: Path) -> QGraphicsScene:
    """
    Final Result view = stacked cropped previews (preview_crop.png) + protein labels.
    v0.1: keep it simple (no legends yet).
    """
    print("DEBUG: render.py build_panel_scene called from:", __file__)
    scene = QGraphicsScene()
    s = project.panel.style
    font = QFont(s.font_family, int(s.font_size_pt))

    if not project.panel.blots:
        scene.addText("No blots in this project.", font)
        return scene

    # Starting position
    x0, y0 = 20.0, 20.0

    # Title (optional)
    title = scene.addText(project.project.name, font)
    title.setDefaultTextColor(Qt.black)
    title.setPos(x0, y0)
    y = y0 + 25

    # Layout constants
    ladder_w = float(s.ladder_col_width_px)
    gap = float(s.gap_between_blots_px)
    protein_w = float(s.protein_col_width_px)

    # Stack in the order specified by layout.order
    order = list(getattr(project.panel.layout, "order", []))
    blot_by_id = {b.id: b for b in project.panel.blots}
    blots = [blot_by_id[i] for i in order if i in blot_by_id] or project.panel.blots

    # Render each cropped blot
    for blot in blots:
        pm = _load_preview_crop_pixmap(workspace_root, blot.asset_sha256)

        # Fallback if preview doesn't exist (should not happen if you regenerate in refresh)
        if pm.isNull():
            pm = _load_original_pixmap(workspace_root, blot.asset_sha256)

        if pm.isNull():
            txt = scene.addText(f"Could not load image for blot: {blot.id}", font)
            txt.setPos(x0, y)
            y += 30
            continue

        # Image position: leave ladder column on left, protein label column on right
        img_x = x0 + ladder_w
        img_item = scene.addPixmap(pm)
        img_item.setPos(img_x, y)

        # Simple protein label on the right
        label = getattr(getattr(blot, "protein_label", None), "text", "")
        if label:
            t = scene.addText(label, font)
            t.setDefaultTextColor(Qt.black)
            t.setPos(img_x + pm.width() + 10, y + pm.height() / 2 - 8)

        # Next row
        y += pm.height() + gap

    return scene


def build_provenance_scene(project: Project, workspace_root: Path, on_crop_commit=None) -> QGraphicsScene:
    """
    Provenance view = full copied original blot + (optional) membrane overlay + crop rectangle.
    v0.1: uses the first blot in the project.
    """
    scene = QGraphicsScene()
    s = project.panel.style
    font = QFont(s.font_family, int(s.font_size_pt))

    if not project.panel.blots:
        scene.addText("No blots in this project.", font)
        return scene

    blot = project.panel.blots[0]

    pm = _load_original_pixmap(workspace_root, blot.asset_sha256)
    if pm.isNull():
        scene.addText(
            "Could not load blot image from workspace assets.\n"
            "Try importing a PNG/JPG first; TIFF 16-bit may require a different loader.",
            font
        )
        return scene

    # Full blot image
    x0, y0 = 10.0, 10.0
    img_item = scene.addPixmap(pm)
    img_item.setPos(x0, y0)

    # Optional membrane overlay (same size/alignment expected)
    overlay_sha = getattr(blot, "overlay_asset_sha256", None)
    overlay_visible = getattr(getattr(blot, "display", None), "overlay_visible", True)
    overlay_alpha = float(getattr(getattr(blot, "display", None), "overlay_alpha", 0.35))

    if overlay_sha and overlay_visible:
        ov = _load_original_pixmap(workspace_root, overlay_sha)
        if not ov.isNull():
            ov_item = scene.addPixmap(ov)
            ov_item.setOpacity(overlay_alpha)
            ov_item.setPos(x0, y0)

    # Crop box overlay (crop coords are in image pixel space)
    c = blot.crop

    def _apply_crop_from_scene_rect(scene_rect: QRectF) -> None:
        # Convert scene coords -> image pixel coords
        x = float(scene_rect.x() - x0)
        y = float(scene_rect.y() - y0)
        w = float(scene_rect.width())
        h = float(scene_rect.height())

        # Optional: clamp into image bounds (recommended)
        if w < 1: w = 1
        if h < 1: h = 1
        if x < 0: x = 0
        if y < 0: y = 0
        if x + w > pm.width():  x = max(0.0, float(pm.width()) - w)
        if y + h > pm.height(): y = max(0.0, float(pm.height()) - h)

        blot.crop.x = x
        blot.crop.y = y
        blot.crop.w = w
        blot.crop.h = h

    crop_rect = QRectF(
        x0 + float(c.x),
        y0 + float(c.y),
        float(c.w),
        float(c.h)
    )

    rect_item = CropRectItem(
        crop_rect,
        on_change=_apply_crop_from_scene_rect,
        on_commit=lambda r: ( _apply_crop_from_scene_rect(r), on_crop_commit(blot) ) if callable(on_crop_commit) else _apply_crop_from_scene_rect(r)
    )
    scene.addItem(rect_item)

    return scene